name: 'Upload File to Google Drive using OAuth2 Credentials'
description: 'Github Action To Upload Github-Actions File to Google Drive Using A Google Drive OAuth Credential!'
inputs:
  client_id:
    description: 'Google OAuth2 Client Id'
    required: true
  client_secret:
    description: 'Google OAuth2 Client Secret'
    required: true
  redirect_uri:
    description: 'Google OAuth2 Redirect URI'
    required: true
  credentials:
    description: 'Google OAuth2 account credentials'
    required: true
  parent_folder_id:
    description: 'Google Drive folder ID to upload the file to'
    required: true
  target:
    description: 'Local path to the file to upload'
    required: true
  name:
    description: 'Optional name for the target file'
    required: false
    default: null
  child_folder:
    description: 'Optional sub-folder to upload the file to (Will be created if non-existent)'
    required: false
    default: null
  override:
    description: 'Optional, if set true, delete files with the same name before uploading'
    required: false
    default: false
    type: boolean
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: upload-cloud
  color: green
